version: "3.3"
services:
  app:
    build: .
    image: alexandreroman/cn-stateless
    environment:
      # Enable profile "cloud".
      - SPRING_PROFILES_ACTIVE=cloud
    links:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:app.stateless.cloudnative"
      - "traefik.backend.healthcheck.path=/actuator/health"

  # Store session attributes in a shared Redis datastore.
  redis:
    image: "redis:5"
    labels:
      - "traefik.enable=false"

  # Use Traefik as a reverse proxy for all app instances.
  reverse_proxy:
    image: "traefik:1.7-alpine"
    # Set Traefik options:
    #  - web:    enable Traefik console
    #  - docker: listen to Docker events
    command: --web --docker
    labels:
      - "traefik.enable=false"
    ports:
      # Public port.
      - "8090:80"
      # Console port.
      - "9000:8080"
    volumes:
      # Give access to Docker events from Traefik.
      - /var/run/docker.sock:/var/run/docker.sock
