---
apiVersion: v1
kind: Service
metadata:
  name: cn-config-lb
  labels:
    app: cn-config
  namespace: cn-config
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: app
---
apiVersion: v1
kind: Service
metadata:
  name: sccs
  namespace: cn-config
spec:
  # We need to create a cluster-wide Config Server service,
  # since this instance is used by all app instances.
  ports:
    - name: sccs
      port: 8888
      protocol: TCP
  selector:
    role: sccs
