---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: cn-stateless
spec:
  # We can start many app instances, since each instance is stateless
  # and data is shared using the Redis datastore.
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
        - name: cn-stateless
          image: alexandreroman/cn-stateless
          env:
            # Enable profile "cloud".
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cn-stateless
spec:
  replicas: 1
  selector:
    matchLabels:
      role: redis
  template:
    metadata:
      labels:
        role: redis
    spec:
      containers:
        - name: cn-stateless-redis
          image: redis:5
          ports:
            - containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
