---
apiVersion: v1
kind: Service
metadata:
  name: cn-stateless-lb
  labels:
    app: cn-stateless
  namespace: cn-stateless
spec:
  type: LoadBalancer
  ports:
    # We rely on the native load balancer support from Kubernetes
    # to redirect traffic across all app instances.
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: app
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cn-stateless
spec:
  # We need to create a cluster-wide Redis datastore service,
  # since this instance is used by all app instances.
  ports:
    - name: redis
      port: 6379
      protocol: TCP
  selector:
    role: redis
