---
apiVersion: v1
kind: Service
metadata:
  name: cn-helloworld-lb
  labels:
    app: cn-helloworld
  namespace: cn-helloworld
spec:
  # Expose this app using a load balancer.
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    # Target this app running in a pod using a selector.
    app: cn-helloworld
