spring:
  cloud:
    config:
      server:
        git:
          # Set Git repository location where configuration is stored.
          # The repository follows this layout:
          #   o- ${spring.application.name}
          #   |--- application.properties
          #   |--- application-${profile}.properties
          #   o- ...
          #   |--- application.properties
          uri: https://github.com/alexandreroman/cloudnativeworkshop-config.git
          search-paths: "{application}"
          clone-on-start: true

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.web: DEBUG
