version: "3.3"
services:
  app:
    build: .
    restart: always
    environment:
      # Override the greeting message using an environment variable.
      - MESSAGE="Bonjour le monde!"
    ports:
      - "8090:8080"
